Numpy


In [ ]:
import numpy
arr=numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
print(np.__version__)

1.23.5


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
arr=np.array(42)
print(arr)

42


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[1])

2


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[2]+arr[3])


7


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row: ',arr[0,1])

2nd element on 1st row:  2


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('5th element on 2nd row: ',arr[1,4])

5th element on 2nd row:  10


In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
for x in arr:
  print(x)

1
2
3
4
5


Pandas

In [ ]:
import pandas

In [ ]:
import pandas as pd
mydataset={'cars':['BMW','Volvo','Ford'],
           'passings':[3,7,2]}
myvar = pd.DataFrame(mydataset)
print(myvar)


    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [ ]:
print(pd.__version__)



1.5.3


In [ ]:
import pandas as pd
a = [1,7,2]
pd.Series(a)
print(a)

[1, 7, 2]


In [ ]:
import pandas as pd
a=[1,7,2]
myvar = pd.Series(a,index=['x','y','z'])
print(myvar)

x    1
y    7
z    2
dtype: int64


In [ ]:
import pandas as pd
calories = {'day1':420,'day2':380,'day3':390}
a=pd.Series(calories)
print(a)

day1    420
day2    380
day3    390
dtype: int64


In [ ]:
s = pd.Series([2,-1,3,5])
print(s)

0    2
1   -1
2    3
3    5
dtype: int64


In [ ]:
import numpy as np
np.square(s)

0     4
1     1
2     9
3    25
dtype: int64

In [ ]:
s + [1000,2000,3000,4000]

0    1002
1    1999
2    3003
3    4005
dtype: int64

In [ ]:
s+1000

0    1002
1     999
2    1003
3    1005
dtype: int64

In [ ]:
s<0

0    False
1     True
2    False
3    False
dtype: bool

In [ ]:
#Index Labels
s1=pd.Series([56,23,200,87])
print(s1)
#setting index manually
s1=pd.Series([56,23,200,87],index=["alice","bob","joy","celen"])
print(s1)

0     56
1     23
2    200
3     87
dtype: int64
alice     56
bob       23
joy      200
celen     87
dtype: int64


In [ ]:
#Accessing items in a series
#Specifying the index
print(s1[2])
#Specifying the label
print(s1["bob"])

200
23


In [ ]:
#Accessing using iloc attribute
print(s1.iloc[2])
#Accessing using the loc attribute
print(s1.loc["bob"])

200
23


In [ ]:
#Creating series from python dictionary
weights = {"alice": 68, "bob": 83, "colin": 86,
"darwin": 68}
s2 = pd.Series(weights)
print(s2)

alice     68
bob       83
colin     86
darwin    68
dtype: int64


In [ ]:
#Automatic allignment- When an operation involves multiple Series objects Pandas automatically aligns items
print(s1+s2)

alice     124.0
bob       106.0
celen       NaN
colin       NaN
darwin      NaN
joy         NaN
dtype: float64


In [ ]:
#Do not forget to set the right index labels, else you may get surprising results
s3=pd.Series([1000,1000,1000,1000])
print(s1+s3)

0       NaN
1       NaN
2       NaN
3       NaN
alice   NaN
bob     NaN
celen   NaN
joy     NaN
dtype: float64


In [ ]:
s4=pd.Series(42,["alice","bob","celen"])
print(s4)

alice    42
bob      42
celen    42
dtype: int64


In [ ]:
#Series object can have a name
s5 = pd.Series([83, 68], index=["bob", "alice"],
name="weights")
print(s5)

bob      83
alice    68
Name: weights, dtype: int64
